# Docs: https://github.com/Azure/functions-action

name: Build and deploy Node.js project to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Pfad zum Function App-Projekt
  NODE_VERSION: '22'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # notwendig, um Commits/Tags pushen zu dürfen

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Tags pushen ermöglichen

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present

      # 🧩 Git-Identität setzen
      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 🧩 Änderungen committen, falls durch Build/Install entstanden
      - name: Commit build changes (if any)
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "chore: auto-commit build artifacts"

      # 🧩 Version erhöhen, committen & taggen
      - name: Bump version (patch) and push tag
        run: |
          npm version patch -m "chore(release): %s"
          git push --follow-tags origin main

      # 🧩 Paket für Deployment vorbereiten
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # notwendig für Azure Login via OIDC
      contents: read    # notwendig für checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: |
          unzip release.zip
          rm release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_35574E1EDF944277B166373AE5A106EB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1CC6B171B7924C8FB5CAA886A5B7CF38 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_73B998E336274129B88E4E9C90E51B5E }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'GitHubDeploy'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
